name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # -------- FRONTEND BUILD --------
      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # -------- BACKEND PREP --------
      - name: Install backend deps
        working-directory: backend
        run: npm install

      # -------- SSH SETUP --------
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Debug SSH (verbose)
        run: ssh -vvv -o StrictHostKeyChecking=yes \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo SSH OK" || true

      # -------- SYNC --------
      - name: Sync Frontend Build
        run: |
          rsync -avz --delete \
            frontend/dist/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/align-alternative-therapy/frontend/build/

      - name: Sync Backend Code
        run: |
          rsync -avz --delete \
            backend/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/align-alternative-therapy/backend/

      # -------- RESTART --------
      - name: Install backend deps & restart
        run: |
          ssh -o StrictHostKeyChecking=yes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/align-alternative-therapy/backend
            pm2 restart align-api
            EOF

