name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [frontend, backend]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js for ${{ matrix.project }}
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.project }}/package-lock.json

    - name: Install dependencies
      working-directory: ${{ matrix.project }}
      run: npm install

    - name: Run tests
      if: matrix.project == 'backend'
      working-directory: backend
      run: npm test

    - name: Build frontend
      if: matrix.project == 'frontend'
      working-directory: frontend
      run: npm run build

  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync Frontend Build
      run: |
        rsync -avz --delete frontend/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/align-alternative-therapy/frontend/build/

    - name: Sync Backend Code
      run: |
        rsync -avz --delete backend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/align-alternative-therapy/backend/

    - name: Install backend deps & restart
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/align-alternative-therapy/backend
          npm install
          pm2 restart align-api
        EOF

